### PR TITLE
Add Julia examples!

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Review by Robinlovelace — COMMENTED** [review]
This is so cool! Thank you, let's get it rolling :rocket:

**Comment by asinghvi17** [comment]
Looks like this crashed when calling `reticulate`.

**Comment by Robinlovelace** [comment]
> Looks like this crashed when calling `reticulate`.

Seen that one before. Can you rebase with main?

**Comment by asinghvi17** [comment]
Just tried that - this is built off the latest commit to main

**Comment by felixcremer** [comment]
I guess, the problem is, that Quarto can only run one jupyter process and therefore you have to run python and julia from the same process.

**Comment by asinghvi17** [comment]
That's true, but we shouldn't be running into many library issues here I would think?  We aren't accessing hdf5 or openssl features for instance, which is where most of the issues lie...

**Comment by rafaqz** [comment]
CairoMakie.jl works fine if you use QuartoNotebookRunner.jl when the whole thing is julia based (e.g. all my presentations at [JuliaCon](https://github.com/rafaqz/JuliaCon2024-DD)). But in this case its trying to open the file externally?

**Comment by asinghvi17** [comment]
Hmm maybe we return colorbuffer instead. QuartoNotebookRunner supports R via RCall, but not Python yet I think (I tried my hand at it but it needs a fair bit of work).

**Comment by felixcremer** [comment]
No the problem is, that the quarto process will make a jupyter notebook with a python kernel and will ignore the julia chunks. You need to run the python chunks via PyCall or the Julia chunks via pyjulia

**Comment by felixcremer** [comment]
I also tried to get the QuartoNotebookRunner to work with Python via PythonCall, but even Lilith couldn't help me at the JuliaCon hackathon.

**Comment by felixcremer** [comment]
See this branch for the stalled effort of doing the same we do with RCall also for python https://github.com/felixcremer/QuartoNotebookRunner.jl/tree/fc/pythoncell

**Comment by evetion** [comment]
@Robinlovelace Can you approve the workflow (maybe permanently?)

**Review by Robinlovelace — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Great changes, sure we can get actions working, especially now I've removed renv.

**Pull request merged**
